// Code generated from kitty's gen/rowcolumn-diacritics.txt; DO NOT EDIT.
// https://raw.githubusercontent.com/kovidgoyal/kitty/master/gen/rowcolumn-diacritics.txt
//
// The Unicode placeholder scheme encodes a cell's row and column as combining
// marks appended to U+10EEEE. Index into this table with the 0-based number.

package main

var diacritics = [...]rune{
	0x0305,  // COMBINING OVERLINE
	0x030D,  // COMBINING VERTICAL LINE ABOVE
	0x030E,  // COMBINING DOUBLE VERTICAL LINE ABOVE
	0x0310,  // COMBINING CANDRABINDU
	0x0312,  // COMBINING TURNED COMMA ABOVE
	0x033D,  // COMBINING X ABOVE
	0x033E,  // COMBINING VERTICAL TILDE
	0x033F,  // COMBINING DOUBLE OVERLINE
	0x0346,  // COMBINING BRIDGE ABOVE
	0x034A,  // COMBINING NOT TILDE ABOVE
	0x034B,  // COMBINING HOMOTHETIC ABOVE
	0x034C,  // COMBINING ALMOST EQUAL TO ABOVE
	0x0350,  // COMBINING RIGHT ARROWHEAD ABOVE
	0x0351,  // COMBINING LEFT HALF RING ABOVE
	0x0352,  // COMBINING FERMATA
	0x0357,  // COMBINING RIGHT HALF RING ABOVE
	0x035B,  // COMBINING ZIGZAG ABOVE
	0x0363,  // COMBINING LATIN SMALL LETTER A
	0x0364,  // COMBINING LATIN SMALL LETTER E
	0x0365,  // COMBINING LATIN SMALL LETTER I
	0x0366,  // COMBINING LATIN SMALL LETTER O
	0x0367,  // COMBINING LATIN SMALL LETTER U
	0x0368,  // COMBINING LATIN SMALL LETTER C
	0x0369,  // COMBINING LATIN SMALL LETTER D
	0x036A,  // COMBINING LATIN SMALL LETTER H
	0x036B,  // COMBINING LATIN SMALL LETTER M
	0x036C,  // COMBINING LATIN SMALL LETTER R
	0x036D,  // COMBINING LATIN SMALL LETTER T
	0x036E,  // COMBINING LATIN SMALL LETTER V
	0x036F,  // COMBINING LATIN SMALL LETTER X
	0x0483,  // COMBINING CYRILLIC TITLO
	0x0484,  // COMBINING CYRILLIC PALATALIZATION
	0x0485,  // COMBINING CYRILLIC DASIA PNEUMATA
	0x0486,  // COMBINING CYRILLIC PSILI PNEUMATA
	0x0487,  // COMBINING CYRILLIC POKRYTIE
	0x0592,  // HEBREW ACCENT SEGOL
	0x0593,  // HEBREW ACCENT SHALSHELET
	0x0594,  // HEBREW ACCENT ZAQEF QATAN
	0x0595,  // HEBREW ACCENT ZAQEF GADOL
	0x0597,  // HEBREW ACCENT REVIA
	0x0598,  // HEBREW ACCENT ZARQA
	0x0599,  // HEBREW ACCENT PASHTA
	0x059C,  // HEBREW ACCENT GERESH
	0x059D,  // HEBREW ACCENT GERESH MUQDAM
	0x059E,  // HEBREW ACCENT GERSHAYIM
	0x059F,  // HEBREW ACCENT QARNEY PARA
	0x05A0,  // HEBREW ACCENT TELISHA GEDOLA
	0x05A1,  // HEBREW ACCENT PAZER
	0x05A8,  // HEBREW ACCENT QADMA
	0x05A9,  // HEBREW ACCENT TELISHA QETANA
	0x05AB,  // HEBREW ACCENT OLE
	0x05AC,  // HEBREW ACCENT ILUY
	0x05AF,  // HEBREW MARK MASORA CIRCLE
	0x05C4,  // HEBREW MARK UPPER DOT
	0x0610,  // ARABIC SIGN SALLALLAHOU ALAYHE WASSALLAM
	0x0611,  // ARABIC SIGN ALAYHE ASSALLAM
	0x0612,  // ARABIC SIGN RAHMATULLAH ALAYHE
	0x0613,  // ARABIC SIGN RADI ALLAHOU ANHU
	0x0614,  // ARABIC SIGN TAKHALLUS
	0x0615,  // ARABIC SMALL HIGH TAH
	0x0616,  // ARABIC SMALL HIGH LIGATURE ALEF WITH LAM WITH YEH
	0x0617,  // ARABIC SMALL HIGH ZAIN
	0x0657,  // ARABIC INVERTED DAMMA
	0x0658,  // ARABIC MARK NOON GHUNNA
	0x0659,  // ARABIC ZWARAKAY
	0x065A,  // ARABIC VOWEL SIGN SMALL V ABOVE
	0x065B,  // ARABIC VOWEL SIGN INVERTED SMALL V ABOVE
	0x065D,  // ARABIC REVERSED DAMMA
	0x065E,  // ARABIC FATHA WITH TWO DOTS
	0x06D6,  // ARABIC SMALL HIGH LIGATURE SAD WITH LAM WITH ALEF MAKSURA
	0x06D7,  // ARABIC SMALL HIGH LIGATURE QAF WITH LAM WITH ALEF MAKSURA
	0x06D8,  // ARABIC SMALL HIGH MEEM INITIAL FORM
	0x06D9,  // ARABIC SMALL HIGH LAM ALEF
	0x06DA,  // ARABIC SMALL HIGH JEEM
	0x06DB,  // ARABIC SMALL HIGH THREE DOTS
	0x06DC,  // ARABIC SMALL HIGH SEEN
	0x06DF,  // ARABIC SMALL HIGH ROUNDED ZERO
	0x06E0,  // ARABIC SMALL HIGH UPRIGHT RECTANGULAR ZERO
	0x06E1,  // ARABIC SMALL HIGH DOTLESS HEAD OF KHAH
	0x06E2,  // ARABIC SMALL HIGH MEEM ISOLATED FORM
	0x06E4,  // ARABIC SMALL HIGH MADDA
	0x06E7,  // ARABIC SMALL HIGH YEH
	0x06E8,  // ARABIC SMALL HIGH NOON
	0x06EB,  // ARABIC EMPTY CENTRE HIGH STOP
	0x06EC,  // ARABIC ROUNDED HIGH STOP WITH FILLED CENTRE
	0x0730,  // SYRIAC PTHAHA ABOVE
	0x0732,  // SYRIAC PTHAHA DOTTED
	0x0733,  // SYRIAC ZQAPHA ABOVE
	0x0735,  // SYRIAC ZQAPHA DOTTED
	0x0736,  // SYRIAC RBASA ABOVE
	0x073A,  // SYRIAC HBASA ABOVE
	0x073D,  // SYRIAC ESASA ABOVE
	0x073F,  // SYRIAC RWAHA
	0x0740,  // SYRIAC FEMININE DOT
	0x0741,  // SYRIAC QUSHSHAYA
	0x0743,  // SYRIAC TWO VERTICAL DOTS ABOVE
	0x0745,  // SYRIAC THREE DOTS ABOVE
	0x0747,  // SYRIAC OBLIQUE LINE ABOVE
	0x0749,  // SYRIAC MUSIC
	0x074A,  // SYRIAC BARREKH
	0x07EB,  // NKO COMBINING SHORT HIGH TONE
	0x07EC,  // NKO COMBINING SHORT LOW TONE
	0x07ED,  // NKO COMBINING SHORT RISING TONE
	0x07EE,  // NKO COMBINING LONG DESCENDING TONE
	0x07EF,  // NKO COMBINING LONG HIGH TONE
	0x07F0,  // NKO COMBINING LONG LOW TONE
	0x07F1,  // NKO COMBINING LONG RISING TONE
	0x07F3,  // NKO COMBINING DOUBLE DOT ABOVE
	0x0816,  // SAMARITAN MARK IN
	0x0817,  // SAMARITAN MARK IN-ALAF
	0x0818,  // SAMARITAN MARK OCCLUSION
	0x0819,  // SAMARITAN MARK DAGESH
	0x081B,  // SAMARITAN MARK EPENTHETIC YUT
	0x081C,  // SAMARITAN VOWEL SIGN LONG E
	0x081D,  // SAMARITAN VOWEL SIGN E
	0x081E,  // SAMARITAN VOWEL SIGN OVERLONG AA
	0x081F,  // SAMARITAN VOWEL SIGN LONG AA
	0x0820,  // SAMARITAN VOWEL SIGN AA
	0x0821,  // SAMARITAN VOWEL SIGN OVERLONG A
	0x0822,  // SAMARITAN VOWEL SIGN LONG A
	0x0823,  // SAMARITAN VOWEL SIGN A
	0x0825,  // SAMARITAN VOWEL SIGN SHORT A
	0x0826,  // SAMARITAN VOWEL SIGN LONG U
	0x0827,  // SAMARITAN VOWEL SIGN U
	0x0829,  // SAMARITAN VOWEL SIGN LONG I
	0x082A,  // SAMARITAN VOWEL SIGN I
	0x082B,  // SAMARITAN VOWEL SIGN O
	0x082C,  // SAMARITAN VOWEL SIGN SUKUN
	0x082D,  // SAMARITAN MARK NEQUDAA
	0x0951,  // DEVANAGARI STRESS SIGN UDATTA
	0x0953,  // DEVANAGARI GRAVE ACCENT
	0x0954,  // DEVANAGARI ACUTE ACCENT
	0x0F82,  // TIBETAN SIGN NYI ZLA NAA DA
	0x0F83,  // TIBETAN SIGN SNA LDAN
	0x0F86,  // TIBETAN SIGN LCI RTAGS
	0x0F87,  // TIBETAN SIGN YANG RTAGS
	0x135D,  // ETHIOPIC COMBINING GEMINATION AND VOWEL LENGTH MARK
	0x135E,  // ETHIOPIC COMBINING VOWEL LENGTH MARK
	0x135F,  // ETHIOPIC COMBINING GEMINATION MARK
	0x17DD,  // KHMER SIGN ATTHACAN
	0x193A,  // LIMBU SIGN KEMPHRENG
	0x1A17,  // BUGINESE VOWEL SIGN I
	0x1A75,  // TAI THAM SIGN TONE-1
	0x1A76,  // TAI THAM SIGN TONE-2
	0x1A77,  // TAI THAM SIGN KHUEN TONE-3
	0x1A78,  // TAI THAM SIGN KHUEN TONE-4
	0x1A79,  // TAI THAM SIGN KHUEN TONE-5
	0x1A7A,  // TAI THAM SIGN RA HAAM
	0x1A7B,  // TAI THAM SIGN MAI SAM
	0x1A7C,  // TAI THAM SIGN KHUEN-LUE KARAN
	0x1B6B,  // BALINESE MUSICAL SYMBOL COMBINING TEGEH
	0x1B6D,  // BALINESE MUSICAL SYMBOL COMBINING KEMPUL
	0x1B6E,  // BALINESE MUSICAL SYMBOL COMBINING KEMPLI
	0x1B6F,  // BALINESE MUSICAL SYMBOL COMBINING JEGOGAN
	0x1B70,  // BALINESE MUSICAL SYMBOL COMBINING KEMPUL WITH JEGOGAN
	0x1B71,  // BALINESE MUSICAL SYMBOL COMBINING KEMPLI WITH JEGOGAN
	0x1B72,  // BALINESE MUSICAL SYMBOL COMBINING BENDE
	0x1B73,  // BALINESE MUSICAL SYMBOL COMBINING GONG
	0x1CD0,  // VEDIC TONE KARSHANA
	0x1CD1,  // VEDIC TONE SHARA
	0x1CD2,  // VEDIC TONE PRENKHA
	0x1CDA,  // VEDIC TONE DOUBLE SVARITA
	0x1CDB,  // VEDIC TONE TRIPLE SVARITA
	0x1CE0,  // VEDIC TONE RIGVEDIC KASHMIRI INDEPENDENT SVARITA
	0x1DC0,  // COMBINING DOTTED GRAVE ACCENT
	0x1DC1,  // COMBINING DOTTED ACUTE ACCENT
	0x1DC3,  // COMBINING SUSPENSION MARK
	0x1DC4,  // COMBINING MACRON-ACUTE
	0x1DC5,  // COMBINING GRAVE-MACRON
	0x1DC6,  // COMBINING MACRON-GRAVE
	0x1DC7,  // COMBINING ACUTE-MACRON
	0x1DC8,  // COMBINING GRAVE-ACUTE-GRAVE
	0x1DC9,  // COMBINING ACUTE-GRAVE-ACUTE
	0x1DCB,  // COMBINING BREVE-MACRON
	0x1DCC,  // COMBINING MACRON-BREVE
	0x1DD1,  // COMBINING UR ABOVE
	0x1DD2,  // COMBINING US ABOVE
	0x1DD3,  // COMBINING LATIN SMALL LETTER FLATTENED OPEN A ABOVE
	0x1DD4,  // COMBINING LATIN SMALL LETTER AE
	0x1DD5,  // COMBINING LATIN SMALL LETTER AO
	0x1DD6,  // COMBINING LATIN SMALL LETTER AV
	0x1DD7,  // COMBINING LATIN SMALL LETTER C CEDILLA
	0x1DD8,  // COMBINING LATIN SMALL LETTER INSULAR D
	0x1DD9,  // COMBINING LATIN SMALL LETTER ETH
	0x1DDA,  // COMBINING LATIN SMALL LETTER G
	0x1DDB,  // COMBINING LATIN LETTER SMALL CAPITAL G
	0x1DDC,  // COMBINING LATIN SMALL LETTER K
	0x1DDD,  // COMBINING LATIN SMALL LETTER L
	0x1DDE,  // COMBINING LATIN LETTER SMALL CAPITAL L
	0x1DDF,  // COMBINING LATIN LETTER SMALL CAPITAL M
	0x1DE0,  // COMBINING LATIN SMALL LETTER N
	0x1DE1,  // COMBINING LATIN LETTER SMALL CAPITAL N
	0x1DE2,  // COMBINING LATIN LETTER SMALL CAPITAL R
	0x1DE3,  // COMBINING LATIN SMALL LETTER R ROTUNDA
	0x1DE4,  // COMBINING LATIN SMALL LETTER S
	0x1DE5,  // COMBINING LATIN SMALL LETTER LONG S
	0x1DE6,  // COMBINING LATIN SMALL LETTER Z
	0x1DFE,  // COMBINING LEFT ARROWHEAD ABOVE
	0x20D0,  // COMBINING LEFT HARPOON ABOVE
	0x20D1,  // COMBINING RIGHT HARPOON ABOVE
	0x20D4,  // COMBINING ANTICLOCKWISE ARROW ABOVE
	0x20D5,  // COMBINING CLOCKWISE ARROW ABOVE
	0x20D6,  // COMBINING LEFT ARROW ABOVE
	0x20D7,  // COMBINING RIGHT ARROW ABOVE
	0x20DB,  // COMBINING THREE DOTS ABOVE
	0x20DC,  // COMBINING FOUR DOTS ABOVE
	0x20E1,  // COMBINING LEFT RIGHT ARROW ABOVE
	0x20E7,  // COMBINING ANNUITY SYMBOL
	0x20E9,  // COMBINING WIDE BRIDGE ABOVE
	0x20F0,  // COMBINING ASTERISK ABOVE
	0x2CEF,  // COPTIC COMBINING NI ABOVE
	0x2CF0,  // COPTIC COMBINING SPIRITUS ASPER
	0x2CF1,  // COPTIC COMBINING SPIRITUS LENIS
	0x2DE0,  // COMBINING CYRILLIC LETTER BE
	0x2DE1,  // COMBINING CYRILLIC LETTER VE
	0x2DE2,  // COMBINING CYRILLIC LETTER GHE
	0x2DE3,  // COMBINING CYRILLIC LETTER DE
	0x2DE4,  // COMBINING CYRILLIC LETTER ZHE
	0x2DE5,  // COMBINING CYRILLIC LETTER ZE
	0x2DE6,  // COMBINING CYRILLIC LETTER KA
	0x2DE7,  // COMBINING CYRILLIC LETTER EL
	0x2DE8,  // COMBINING CYRILLIC LETTER EM
	0x2DE9,  // COMBINING CYRILLIC LETTER EN
	0x2DEA,  // COMBINING CYRILLIC LETTER O
	0x2DEB,  // COMBINING CYRILLIC LETTER PE
	0x2DEC,  // COMBINING CYRILLIC LETTER ER
	0x2DED,  // COMBINING CYRILLIC LETTER ES
	0x2DEE,  // COMBINING CYRILLIC LETTER TE
	0x2DEF,  // COMBINING CYRILLIC LETTER HA
	0x2DF0,  // COMBINING CYRILLIC LETTER TSE
	0x2DF1,  // COMBINING CYRILLIC LETTER CHE
	0x2DF2,  // COMBINING CYRILLIC LETTER SHA
	0x2DF3,  // COMBINING CYRILLIC LETTER SHCHA
	0x2DF4,  // COMBINING CYRILLIC LETTER FITA
	0x2DF5,  // COMBINING CYRILLIC LETTER ES-TE
	0x2DF6,  // COMBINING CYRILLIC LETTER A
	0x2DF7,  // COMBINING CYRILLIC LETTER IE
	0x2DF8,  // COMBINING CYRILLIC LETTER DJERV
	0x2DF9,  // COMBINING CYRILLIC LETTER MONOGRAPH UK
	0x2DFA,  // COMBINING CYRILLIC LETTER YAT
	0x2DFB,  // COMBINING CYRILLIC LETTER YU
	0x2DFC,  // COMBINING CYRILLIC LETTER IOTIFIED A
	0x2DFD,  // COMBINING CYRILLIC LETTER LITTLE YUS
	0x2DFE,  // COMBINING CYRILLIC LETTER BIG YUS
	0x2DFF,  // COMBINING CYRILLIC LETTER IOTIFIED BIG YUS
	0xA66F,  // COMBINING CYRILLIC VZMET
	0xA67C,  // COMBINING CYRILLIC KAVYKA
	0xA67D,  // COMBINING CYRILLIC PAYEROK
	0xA6F0,  // BAMUM COMBINING MARK KOQNDON
	0xA6F1,  // BAMUM COMBINING MARK TUKWENTIS
	0xA8E0,  // COMBINING DEVANAGARI DIGIT ZERO
	0xA8E1,  // COMBINING DEVANAGARI DIGIT ONE
	0xA8E2,  // COMBINING DEVANAGARI DIGIT TWO
	0xA8E3,  // COMBINING DEVANAGARI DIGIT THREE
	0xA8E4,  // COMBINING DEVANAGARI DIGIT FOUR
	0xA8E5,  // COMBINING DEVANAGARI DIGIT FIVE
	0xA8E6,  // COMBINING DEVANAGARI DIGIT SIX
	0xA8E7,  // COMBINING DEVANAGARI DIGIT SEVEN
	0xA8E8,  // COMBINING DEVANAGARI DIGIT EIGHT
	0xA8E9,  // COMBINING DEVANAGARI DIGIT NINE
	0xA8EA,  // COMBINING DEVANAGARI LETTER A
	0xA8EB,  // COMBINING DEVANAGARI LETTER U
	0xA8EC,  // COMBINING DEVANAGARI LETTER KA
	0xA8ED,  // COMBINING DEVANAGARI LETTER NA
	0xA8EE,  // COMBINING DEVANAGARI LETTER PA
	0xA8EF,  // COMBINING DEVANAGARI LETTER RA
	0xA8F0,  // COMBINING DEVANAGARI LETTER VI
	0xA8F1,  // COMBINING DEVANAGARI SIGN AVAGRAHA
	0xAAB0,  // TAI VIET MAI KANG
	0xAAB2,  // TAI VIET VOWEL I
	0xAAB3,  // TAI VIET VOWEL UE
	0xAAB7,  // TAI VIET MAI KHIT
	0xAAB8,  // TAI VIET VOWEL IA
	0xAABE,  // TAI VIET VOWEL AM
	0xAABF,  // TAI VIET TONE MAI EK
	0xAAC1,  // TAI VIET TONE MAI THO
	0xFE20,  // COMBINING LIGATURE LEFT HALF
	0xFE21,  // COMBINING LIGATURE RIGHT HALF
	0xFE22,  // COMBINING DOUBLE TILDE LEFT HALF
	0xFE23,  // COMBINING DOUBLE TILDE RIGHT HALF
	0xFE24,  // COMBINING MACRON LEFT HALF
	0xFE25,  // COMBINING MACRON RIGHT HALF
	0xFE26,  // COMBINING CONJOINING MACRON
	0x10A0F, // KHAROSHTHI SIGN VISARGA
	0x10A38, // KHAROSHTHI SIGN BAR ABOVE
	0x1D185, // MUSICAL SYMBOL COMBINING DOIT
	0x1D186, // MUSICAL SYMBOL COMBINING RIP
	0x1D187, // MUSICAL SYMBOL COMBINING FLIP
	0x1D188, // MUSICAL SYMBOL COMBINING SMEAR
	0x1D189, // MUSICAL SYMBOL COMBINING BEND
	0x1D1AA, // MUSICAL SYMBOL COMBINING DOWN BOW
	0x1D1AB, // MUSICAL SYMBOL COMBINING UP BOW
	0x1D1AC, // MUSICAL SYMBOL COMBINING HARMONIC
	0x1D1AD, // MUSICAL SYMBOL COMBINING SNAP PIZZICATO
	0x1D242, // COMBINING GREEK MUSICAL TRISEME
	0x1D243, // COMBINING GREEK MUSICAL TETRASEME
	0x1D244, // COMBINING GREEK MUSICAL PENTASEME
}
